# Generated by Django 2.2.14 on 2020-11-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
