# Generated by Django 2.2.14 on 2020-11-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('docente', models.CharField(max_length=150)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
