# Generated by Django 2.2.14 on 2020-11-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='docente',
        ),
        migrations.AddField(
            model_name='clase',
            name='docente',
            field=models.ManyToManyField(related_name='clases', to='docentes.Docente'),
        ),
    ]
